# Generated by Django 4.2.5 on 2023-09-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehilculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6)),
                ('modelo', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
    ]
